name: test

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

concurrency:
  group: "test-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test-uv:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]
        os: [ "ubuntu-latest", "macos-latest" ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: PyPi os=${{ matrix.os }} - python=${{ matrix.python-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-groups --python ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest

      - name: Test CLI
        run: uv run vcb --help
